def notTrained():
    dic1 = {'algerianhostagecrisis': ['algerian', 'hostage', 'crisis'],
            'australianguncontrol': ['australian', 'gun', 'control'],
            'australiansecurityandcounterterrorism': ['security', 'counter', 'terrorism'],
            'bastilledaytruckattack': ['bastille', 'truck'],
            'berlinchristmasmarketattack': ['berlin', 'christmas', 'market'],
            'bostonmarathonbombing': ['boston', 'marathon'],
            'brusselsattacks': ['brussels'],
            'charliehebdoattack': ['hebdo'],
            'clusterbombs': ['clusterbombs'],
            'europeanarrestwarrant': ['european', 'arrest', 'warrant'],
            'francetrainattack': ['france', 'train'],
            'jubilee': ['jubilee'],
            'mumbaiterrorattacks': ['mumbai'],
            'munichshooting': ['munich', 'shooting'],
            'orlandoterrorattack': ['orlando'],
            'parisattacks': ['paris'],
            'peaceandreconciliation': ['peace', 'reconciliation'],
            'rio20earthsummit': ['rio', 'summit'],
            'sanbernardinoshooting': ['san', 'bernardino'],
            'sydneysiege': ['sydney', 'siege'],
            'tunisiaattack2015': ['tunisia'],
            'turkeycoupattempt': ['turkey', 'coup'],
            'zikavirus': ['zikavirus']}
    return(dic1)
